import { h } from '../lib/helpers';

export function renderWatchComments(animeId:number,episodeNum:number,siteUrl:string,isLoggedIn:boolean):string {
  const loginUrl = siteUrl + '/login';
  return '<style>' +
  '.av-comments{margin:34px 0 12px;padding:0;background:#000;border:0;border-radius:0;color:var(--text-primary)}' +
  '.avc-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:0 0 18px;border-bottom:1px solid rgba(255,255,255,.08)}' +
  '.avc-title{display:flex;align-items:center;gap:10px;font-size:1.55rem;font-weight:850;letter-spacing:-.035em;text-transform:uppercase}.avc-count{display:inline-flex;align-items:center;justify-content:center;min-width:42px;height:28px;padding:0 10px;border-radius:999px;background:var(--accent);color:#fff;font-size:.82rem;font-weight:900;letter-spacing:0;text-transform:none}' +
  '.avc-sort{position:relative}.avc-sort-btn{height:42px;display:inline-flex;align-items:center;gap:10px;padding:0 16px;border:0;border-radius:10px;background:var(--surface-2,#18181b);color:var(--text-primary,#f4f4f5);font:500 .9rem var(--font-body);cursor:pointer}.avc-sort-btn svg{width:17px;height:17px}.avc-sort-menu{position:absolute;right:0;top:48px;z-index:20;min-width:150px;padding:6px;border:1px solid rgba(255,255,255,.09);border-radius:10px;background:var(--surface-2,#18181b);box-shadow:0 18px 45px rgba(0,0,0,.5);display:none}.avc-sort-menu.open{display:block}.avc-sort-option{width:100%;display:block;padding:9px 11px;border:0;border-radius:7px;background:transparent;color:var(--text-secondary,#a1a1aa);text-align:left;font:500 .78rem var(--font-body);cursor:pointer}.avc-sort-option:hover,.avc-sort-option.active{background:rgba(255,255,255,.07);color:#fff}' +
  '.avc-compose{display:flex;align-items:flex-start;gap:15px;margin:0 0 34px}.avc-compose-avatar,.avc-avatar{width:44px;height:44px;flex:0 0 44px;border-radius:50%;object-fit:cover;background:radial-gradient(circle at 35% 30%,#d9d9df,#5d5d68 55%,#202027);overflow:hidden}.avc-compose-main{flex:1;min-width:0}.avc-compose textarea{box-sizing:border-box;width:100%;min-height:156px;max-height:280px;resize:vertical;background:#09090a;border:1px solid #29292d;border-radius:13px;color:#e5e7eb;padding:18px 20px;font:500 1rem/1.5 var(--font-body);outline:none}.avc-compose textarea::placeholder{color:var(--text-muted,#777782)}.avc-compose textarea:focus{border-color:#4a4a50;box-shadow:0 0 0 2px rgba(255,255,255,.02)}.avc-compose-actions{display:flex;justify-content:flex-end;margin-top:8px}.avc-compose button{border:0;border-radius:999px;padding:9px 22px;background:var(--accent);color:#fff;font:800 .78rem var(--font-body);cursor:pointer}.avc-compose button:hover{filter:brightness(1.08)}.avc-login{padding:14px 16px;border-radius:12px;background:#111113;color:#9b9ba3;margin:0 0 24px}.avc-login a{color:var(--accent);font-weight:800}' +
  '.avc-list-head{margin:0 0 24px;color:var(--text-secondary,#a1a1aa);font-size:1.15rem;font-weight:500}.avc-list{display:flex;flex-direction:column;gap:0}.avc-item{position:relative;margin:0 0 22px;padding:0 0 0 0}.avc-item.reply{margin:0 0 8px 46px;padding-left:0}.avc-comment{position:relative;padding-left:58px}.avc-item.reply .avc-comment{padding-left:45px}.avc-top{display:flex;align-items:center;gap:10px;min-height:44px}.avc-avatar{position:absolute;left:0;top:0;width:44px;height:44px}.avc-item.reply .avc-avatar{width:34px;height:34px;top:2px}.avc-user{font-weight:850;font-size:.9rem;color:var(--text-primary,#d4d4d8)}.avc-user.owner{color:var(--accent)}.avc-user.admin{color:var(--accent)}.avc-badge{display:none}.avc-time{color:#777782;font-size:.78rem}.avc-body{margin:10px 0 13px;color:var(--text-primary,#d0d0d6);white-space:pre-wrap;word-break:break-word;line-height:1.52;font-size:1rem}.avc-item.reply .avc-body{font-size:.94rem;margin-top:8px}.avc-actions{display:flex;align-items:center;gap:22px;min-height:32px}.avc-btn{display:inline-flex;align-items:center;gap:6px;border:0;background:transparent;color:#a1a1aa;cursor:pointer;padding:3px 0;border-radius:6px;font:700 .78rem var(--font-body)}.avc-btn:hover{color:#fff}.avc-btn.on{color:var(--accent)}.avc-btn svg{width:20px;height:20px;stroke:currentColor;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.avc-more{margin-left:auto;position:relative}.avc-more-menu{position:absolute;right:0;bottom:28px;z-index:15;display:none;min-width:120px;padding:5px;border:1px solid rgba(255,255,255,.1);border-radius:9px;background:#18181b;box-shadow:0 15px 35px rgba(0,0,0,.5)}.avc-more-menu.open{display:block}.avc-more-menu button{width:100%;padding:8px 10px;border:0;border-radius:6px;background:transparent;color:var(--accent);text-align:left;font:700 .76rem var(--font-body);cursor:pointer}.avc-more-menu button:hover{background:color-mix(in srgb,var(--accent) 12%,transparent)}' +
  '.avc-thread{position:relative;margin-left:23px;padding-left:0}.avc-thread:before{content:"";position:absolute;left:0;top:0;bottom:18px;width:1px;background:rgba(255,255,255,.12)}.avc-thread .avc-item{padding-left:44px}.avc-thread .avc-item:before{content:"";position:absolute;left:0;top:23px;width:30px;height:20px;border-left:1px solid #25252a;border-bottom:1px solid #25252a;border-radius:0 0 0 14px}.avc-replies-toggle{display:inline-flex;align-items:center;gap:8px;margin:3px 0 5px 68px;padding:5px 0;border:0;background:transparent;color:#a1a1aa;font:800 .8rem var(--font-body);cursor:pointer}.avc-replies-toggle:hover{color:#fff}.avc-replies-toggle svg{width:14px;height:14px;stroke:currentColor;fill:none;stroke-width:2}.avc-replybox{margin:10px 0 12px 58px;display:none;gap:8px}.avc-replybox.open{display:flex}.avc-replybox input{flex:1;background:var(--surface-1,#0b0b0d);border:1px solid rgba(255,255,255,.12);border-radius:9px;color:#fff;padding:9px 11px;font:inherit;font-size:.8rem;outline:none}.avc-replybox button{border:0;border-radius:999px;padding:0 15px;background:var(--accent);color:#fff;font-weight:800;cursor:pointer}.avc-error{color:#f87171;font-size:.78rem;margin:8px 0}.avc-loading{color:#777782;padding:20px 0;text-align:center}.avc-empty{color:#777782;padding:20px 0}.avc-deleted{color:#777782;font-style:italic}' +
  '@media(max-width:600px){.av-comments{margin-top:26px}.avc-title{font-size:1.35rem}.avc-count{height:25px;min-width:36px;font-size:.75rem}.avc-sort-btn{height:39px;padding:0 12px;font-size:.82rem}.avc-compose{gap:10px}.avc-compose-avatar{width:38px;height:38px;flex-basis:38px}.avc-compose textarea{min-height:135px;padding:15px;font-size:.92rem}.avc-list-head{font-size:1.05rem}.avc-avatar{width:36px;height:36px;flex-basis:36px}.avc-comment{padding-left:48px}.avc-item.reply{margin-left:26px}.avc-item.reply .avc-comment{padding-left:40px}.avc-item.reply .avc-avatar{width:30px;height:30px}.avc-body{font-size:.94rem}.avc-actions{gap:16px}.avc-thread{margin-left:10px}.avc-thread .avc-item{padding-left:27px}.avc-thread .avc-item:before{width:20px}.avc-replies-toggle{margin-left:47px}.avc-replybox{margin-left:48px}}' +
  '</style>' +
  '<section class="av-comments" id="watch-comments" data-anime-id="' + animeId + '" data-episode="' + episodeNum + '">' +
    '<div class="avc-head"><div class="avc-title">Comments <span class="avc-count" id="avc-count"></span></div><div class="avc-sort"><button type="button" class="avc-sort-btn" id="avc-sort-btn">Newest <span>⌄</span></button><div class="avc-sort-menu" id="avc-sort-menu"><button class="avc-sort-option active" data-sort="newest">Newest</button><button class="avc-sort-option" data-sort="oldest">Oldest</button><button class="avc-sort-option" data-sort="top">Top</button></div></div></div>' +
    (isLoggedIn
      ? '<div class="avc-compose"><div class="avc-compose-avatar" id="avc-compose-avatar"></div><div class="avc-compose-main"><textarea id="avc-input" maxlength="1000" placeholder="Write your comment..."></textarea><div class="avc-compose-actions"><button type="button" data-avc-action="send">Comment</button></div></div></div>'
      : '<div class="avc-login">Want to join the discussion? <a href="' + h(loginUrl) + '">Log in</a> to comment, reply, like or dislike.</div>') +
    '<div class="avc-error" id="avc-error"></div><div class="avc-list-head" id="avc-list-head">0 comments</div><div class="avc-list" id="avc-list"><div class="avc-loading">Loading comments…</div></div>' +
  '</section>' +
  '';
}