import { Hono } from 'hono';
import { authRoutes } from './routes/auth';
import { homeRoutes } from './routes/home';
import { browseRoutes } from './routes/browse';
import { discoverRoutes } from './routes/discover';
import { animeRoutes } from './routes/anime';
import { characterRoutes } from './routes/character';
import { watchRoutes } from './routes/watch';
import { listRoutes } from './routes/lists';
import { apiListRoutes } from './routes/api-lists';
import { importExportRoutes } from './routes/importexport';
import { profileRoutes } from './routes/profile';
import { avatarRoutes } from './routes/avatar';
import { userRoutes } from './routes/user';
import { adminIndexRoutes } from './routes/admin/index';
import { impersonateRoutes } from './routes/admin/impersonate';
import { adminUsersRoutes } from './routes/admin/users';
import { adminEpisodesRoutes } from './routes/admin/episodes';
import { episodeOverrideRoutes } from './routes/api-episode-override';
import { adminVideosRoutes } from './routes/admin/videos';
import { apiVideosRoutes } from './routes/api-videos';
import { adminEpThumbnailsRoutes } from './routes/admin/ep-thumbnails';
import { thumbSearchRoutes } from './routes/api-thumb-search';
import { adminMiscSmallRoutes } from './routes/admin/misc-small';
import { adminAnnouncementsRoutes } from './routes/admin/announcements';
import { adminAnimeImagesRoutes } from './routes/admin/anime-images';
import { adminMergeUsersRoutes } from './routes/admin/merge-users';
import { adminUsernameFixerRoutes } from './routes/admin/username-fixer';
import { adminAnalyticsRoutes } from './routes/admin/analytics';
import { adminFeedbackRoutes } from './routes/admin/feedback';
import { adminBadgesRoutes } from './routes/admin/badges';
import { adminSurveyRoutes } from './routes/admin/survey';
import { adminCacheRoutes } from './routes/admin/cache';
import { adminWatchStatsRoutes } from './routes/admin/watch-stats';
import { adminHealImagesRoutes } from './routes/admin/heal-images';
import { scraperRoutes } from './routes/api-scraper';

// Env bindings + secrets (set secrets via `wrangler secret put NAME`, see wrangler.toml)
export interface Env {
  DB: D1Database;
  API_CACHE: KVNamespace;
  AVATARS: R2Bucket;
  SITE_NAME: string;
  SITE_URL: string;
  SESSION_LIFETIME_SECONDS: string;
  API_CACHE_ENABLED?: string;
  API_CACHE_TIME?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  GOOGLE_REDIRECT_URI?: string;
  DISCORD_CLIENT_ID?: string;
  DISCORD_CLIENT_SECRET?: string;
  DISCORD_REDIRECT_URI?: string;
  DISCORD_SERVER_ID?: string;
  DISCORD_BOT_TOKEN?: string;
  DISCORD_RELAY_URL?: string;
  BOT_SECRET?: string;
  MAL_CLIENT_ID?: string;
  MAL_CLIENT_SECRET?: string;
  TMDB_API_KEY?: string;
}

const app = new Hono<{ Bindings: Env }>();

app.route('/', authRoutes);
app.route('/', homeRoutes);
app.route('/', browseRoutes);
app.route('/', discoverRoutes);
app.route('/', animeRoutes);
app.route('/', characterRoutes);
app.route('/', watchRoutes);
app.route('/', listRoutes);
app.route('/', apiListRoutes);
app.route('/', importExportRoutes);
app.route('/', profileRoutes);
app.route('/', avatarRoutes);
app.route('/', userRoutes);
app.route('/', adminIndexRoutes);
app.route('/', impersonateRoutes);
app.route('/', adminUsersRoutes);
app.route('/', adminEpisodesRoutes);
app.route('/', episodeOverrideRoutes);
app.route('/', adminVideosRoutes);
app.route('/', apiVideosRoutes);
app.route('/', adminEpThumbnailsRoutes);
app.route('/', thumbSearchRoutes);
app.route('/', adminMiscSmallRoutes);
app.route('/', adminAnnouncementsRoutes);
app.route('/', adminAnimeImagesRoutes);
app.route('/', adminMergeUsersRoutes);
app.route('/', adminUsernameFixerRoutes);
app.route('/', adminAnalyticsRoutes);
app.route('/', adminFeedbackRoutes);
app.route('/', adminBadgesRoutes);
app.route('/', adminSurveyRoutes);
app.route('/', adminCacheRoutes);
app.route('/', adminWatchStatsRoutes);
app.route('/', adminHealImagesRoutes);
app.route('/', scraperRoutes);

export default app;
